package com.airis.message.entity;

import com.airis.message.enums.MessageStatus;
import com.airis.message.enums.MessageType;
import com.airis.message.enums.ModerationStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Map;

/**
 * MongoDB chat message entity
 * 
 * @author AIRIS Team
 * @since 1.0.0
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "chat_messages")
@CompoundIndex(def = "{'chatId': 1, 'timestamp': -1}")
public class ChatMessage {

    /**
     * MongoDB document ID
     */
    @Id
    private String id;

    /**
     * Global message ID (generated by snowflake algorithm)
     */
    @Indexed(unique = true)
    private String messageId;

    /**
     * Chat ID
     */
    @Indexed
    private String chatId;

    /**
     * Sender ID
     */
    private String senderId;

    /**
     * Receiver ID
     */
    private String receiverId;

    /**
     * Message type
     */
    private MessageType messageType;

    /**
     * Message content
     */
    private String content;

    /**
     * Media file metadata
     */
    private MediaMetadata mediaMetadata;

    /**
     * Server received message timestamp
     */
    private Long timestamp;

    /**
     * Client sent timestamp
     */
    private Long clientTimestamp;

    /**
     * Message status
     */
    private MessageStatus status;

    /**
     * Content moderation status
     */
    private ModerationStatus moderationStatus;

    /**
     * Extended data
     */
    private Map<String, Object> extraData;

    /**
     * Media file metadata
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class MediaMetadata {
        /**
         * File URL
         */
        private String url;

        /**
         * File name
         */
        private String fileName;

        /**
         * File size
         */
        private Long fileSize;

        /**
         * Duration in seconds
         */
        private Integer duration;

        /**
         * Width
         */
        private Integer width;

        /**
         * Height
         */
        private Integer height;
    }
}