server:
  port: 8088

spring:
  application:
    name: gateway-service
  main:
    #允许循环引用
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        server-addr: 10.144.113.108:8848
        namespace: public
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: false  # 禁用自动发现路由
          lower-case-service-id: true
      routes:
      #enabled: false才能避免StripPrefix

        # 匹配服务路由 - 直接路由到 match-service
        - id: match-service
          uri: lb://match-service
          predicates:
            - Path=/api/v1/match/**
          filters:
            - name: AuthFilter

        # 用户服务路由
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: AuthFilter

        # 用户交互服务路由（点赞、评论等）
        - id: user-interaction-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/interact/**
          filters:
            - name: AuthFilter

        # 认证相关路由（不需要认证）
        - id: auth-routes
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**
          # 移除限流器

        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/v1/messages/**
          filters:
            - name: AuthFilter

        # 聊天相关路由
        - id: chat-service
          uri: lb://realtime-chat-service
          predicates:
            - Path=/api/chat/**
          filters:
            - name: AuthFilter

        # WebSocket 路由
        - id: websocket-chat
          uri: lb://realtime-chat-service
          predicates:
            - Path=/ws/chat/**
          # 移除限流器

        # media服务静态路由
        - id: media
          uri: lb://media
          predicates:
            - Path=/media/**
          filters:
            - name: AuthFilter

        - id: notification
          uri: lb://notification
          predicates:
            - Path=/notifications/**
          filters:
            - name: AuthFilter

        - id: websocket-notification
          uri: lb://notification  # 或者直接用 http://10.144.122.245:8082
          predicates:
            - Path=/ws/**  # 或者更具体的路径如 /ws/notification/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://10.144.1.1:5173"
              - "http://10.144.1.1:3000"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
        add-to-simple-url-handler-mapping: true

  # redis:
  #   host: 10.144.113.108
  #   port: 6379
  #   database: 0
  #   timeout: 2000ms
  #   lettuce:
  #     pool:
  #       max-active: 8
  #       max-idle: 8
  #       min-idle: 0


# JWT配置
jwt:
  secret: Y2xvZGVkX2tleV9mb3Jfand0X3NpZ25pbmdfcmVhbF9zYWZldHk=
  expiration: 86400000

# 日志配置
logging:
  level:
    root: INFO
    com.airis.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG
    org.springframework.cloud.gateway.filter.ratelimit: TRACE
    org.springframework.data.redis: DEBUG
    io.lettuce: DEBUG
    reactor.netty: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

